/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.DijkstraMapSql;
import java.awt.event.KeyEvent;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Hadaragama
 */
public class DijkstraMap extends javax.swing.JFrame {

    int[] value;
    int[] shortest;
    int[] inputs;
    String[] saveInput;
    String[] cityConnections;
    static int uid;
    static String uname;
    String point;

    /**
     * Creates new form Test
     */
    public DijkstraMap(int uid, String uname, int val[], String point, int shortest[]) {

        initComponents();
        this.point = point;
        this.uname = uname;
        this.uid = uid;
        lbl_userName.setText(uname);
        this.value = val;
        this.shortest = shortest;
        lbl_instruction2.setText("Question : Calculate the shortest path to each city from city " + point);
        lblAB.setText("" + value[0] + " km");
        lblAI.setText("" + value[1] + " km");
        lblBI.setText("" + value[2] + " km");
        lblBC.setText("" + value[3] + " km");
        lblCD.setText("" + value[4] + " km");
        lblID.setText("" + value[5] + " km");
        lblDE.setText("" + value[6] + " km");
        lblHE.setText("" + value[7] + " km");
        lblEF.setText("" + value[8] + " km");
        lblHF.setText("" + value[9] + " km");
        lblFG.setText("" + value[10] + " km");
        lblHG.setText("" + value[11] + " km");
        lblIH.setText("" + value[12] + " km");
        cityConnections = new String[]{" A to B", Integer.toString(value[0]),
            " A to I", Integer.toString(value[1]),
            " B to I", Integer.toString(value[2]),
            " B to C", Integer.toString(value[3]),
            " C to D", Integer.toString(value[4]),
            " I to D", Integer.toString(value[5]),
            " D to E", Integer.toString(value[6]),
            " H to E", Integer.toString(value[7]),
            " E to F", Integer.toString(value[8]),
            " H to F", Integer.toString(value[9]),
            " F to G", Integer.toString(value[10]),
            " H to G", Integer.toString(value[11]),
            " I to H", Integer.toString(value[12])};
        lbl1.setText(point);
        lbl2.setText(point);
        lbl3.setText(point);
        lbl4.setText(point);
        lbl5.setText(point);
        lbl6.setText(point);
        lbl7.setText(point);
        lbl8.setText(point);
        lbl9.setText(point);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        lbl_userID = new javax.swing.JLabel();
        lbl_close = new javax.swing.JLabel();
        lbl_userName = new javax.swing.JLabel();
        lbl_userName1 = new javax.swing.JLabel();
        lbl_close3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnSubmit = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblAB = new javax.swing.JLabel();
        lblBC = new javax.swing.JLabel();
        lblCD = new javax.swing.JLabel();
        lblDE = new javax.swing.JLabel();
        lblEF = new javax.swing.JLabel();
        lblFG = new javax.swing.JLabel();
        lblHF = new javax.swing.JLabel();
        lblHE = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblBI = new javax.swing.JLabel();
        lblAI = new javax.swing.JLabel();
        lblIH = new javax.swing.JLabel();
        lblHG = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_instruction2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lbl7 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lbl8 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        lbl9 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        resultA = new javax.swing.JTextField();
        resultE = new javax.swing.JTextField();
        resultC = new javax.swing.JTextField();
        resultG = new javax.swing.JTextField();
        resultI = new javax.swing.JTextField();
        resultB = new javax.swing.JTextField();
        resultD = new javax.swing.JTextField();
        resultF = new javax.swing.JTextField();
        resultH = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        lbl_instruction1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(560, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(12, 19, 79));

        lbl_userID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_userID.setForeground(new java.awt.Color(255, 255, 255));
        lbl_userID.setText("Hello");

        lbl_close.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbl_close.setForeground(new java.awt.Color(255, 255, 255));
        lbl_close.setText("X");
        lbl_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_closeMouseClicked(evt);
            }
        });

        lbl_userName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_userName.setForeground(new java.awt.Color(255, 255, 255));
        lbl_userName.setText("UserName");

        lbl_userName1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_userName1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_userName1.setText("Find Minimum Connectors");

        lbl_close3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lbl_close3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_close3.setText("<Back");
        lbl_close3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_close3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbl_userID)
                .addGap(2, 2, 2)
                .addComponent(lbl_userName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(lbl_userName1)
                .addGap(73, 73, 73)
                .addComponent(lbl_close3)
                .addGap(18, 18, 18)
                .addComponent(lbl_close)
                .addGap(14, 14, 14))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_close)
                    .addComponent(lbl_close3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_userID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_userName)
                    .addComponent(lbl_userName1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(560, 700));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSubmit.setBackground(new java.awt.Color(204, 255, 255));
        btnSubmit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(12, 19, 79));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        jPanel4.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 660, -1, -1));

        btn_clear.setBackground(new java.awt.Color(204, 255, 255));
        btn_clear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_clear.setForeground(new java.awt.Color(12, 19, 79));
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        jPanel4.add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 660, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAB.setText("x");
        jPanel1.add(lblAB, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 40, 20));

        lblBC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblBC.setText("x");
        jPanel1.add(lblBC, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 60, 20));

        lblCD.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCD.setText("x");
        jPanel1.add(lblCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 50, 20));

        lblDE.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDE.setText("x");
        jPanel1.add(lblDE, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 60, 20));

        lblEF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEF.setText("x");
        jPanel1.add(lblEF, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 50, 20));

        lblFG.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFG.setText("x");
        jPanel1.add(lblFG, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 60, 20));

        lblHF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHF.setText("x");
        jPanel1.add(lblHF, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 50, 20));

        lblHE.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHE.setText("x");
        jPanel1.add(lblHE, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 50, 20));

        lblID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblID.setText("x");
        jPanel1.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 50, 20));

        lblBI.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblBI.setText("x");
        jPanel1.add(lblBI, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 60, 20));

        lblAI.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAI.setText("x");
        jPanel1.add(lblAI, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 50, 20));

        lblIH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblIH.setText("x");
        jPanel1.add(lblIH, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 60, 20));

        lblHG.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHG.setText("x");
        jPanel1.add(lblHG, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 50, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chamod Dilushanka\\Downloads\\path.png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 6, 370, 350));

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 380, 360));

        lbl_instruction2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_instruction2.setText("............................................................................................................................");
        jPanel4.add(lbl_instruction2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 448, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("From");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(12, 19, 79));
        jLabel4.setText("A :");

        lbl1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl1.setForeground(new java.awt.Color(12, 19, 79));
        lbl1.setText("A");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("to");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("From");

        lbl3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl3.setForeground(new java.awt.Color(12, 19, 79));
        lbl3.setText("A");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("to");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(12, 19, 79));
        jLabel10.setText("C :");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(12, 19, 79));
        jLabel11.setText("E :");

        lbl5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl5.setForeground(new java.awt.Color(12, 19, 79));
        lbl5.setText("A");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("From");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("to");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(12, 19, 79));
        jLabel15.setText("G :");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("From");

        lbl7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl7.setForeground(new java.awt.Color(12, 19, 79));
        lbl7.setText("A");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("to");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("to");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("From");

        lbl8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl8.setForeground(new java.awt.Color(12, 19, 79));
        lbl8.setText("A");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(12, 19, 79));
        jLabel22.setText("H :");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("From");

        lbl6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl6.setForeground(new java.awt.Color(12, 19, 79));
        lbl6.setText("A");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setText("to");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(12, 19, 79));
        jLabel26.setText("F :");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setText("From");

        lbl4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl4.setForeground(new java.awt.Color(12, 19, 79));
        lbl4.setText("A");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel29.setText("to");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(12, 19, 79));
        jLabel30.setText("D :");

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel31.setText("From");

        lbl2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl2.setForeground(new java.awt.Color(12, 19, 79));
        lbl2.setText("A");

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel33.setText("to");

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(12, 19, 79));
        jLabel34.setText("B :");

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel36.setText("From");

        lbl9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl9.setForeground(new java.awt.Color(12, 19, 79));
        lbl9.setText("A");

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel38.setText("to");

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(12, 19, 79));
        jLabel39.setText("I :");

        resultA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultAActionPerformed(evt);
            }
        });
        resultA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                resultAKeyPressed(evt);
            }
        });

        resultE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultEActionPerformed(evt);
            }
        });
        resultE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                resultEKeyPressed(evt);
            }
        });

        resultC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultCActionPerformed(evt);
            }
        });
        resultC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                resultCKeyPressed(evt);
            }
        });

        resultG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultGActionPerformed(evt);
            }
        });
        resultG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                resultGKeyPressed(evt);
            }
        });

        resultI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultIActionPerformed(evt);
            }
        });
        resultI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                resultIKeyPressed(evt);
            }
        });

        resultB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultBActionPerformed(evt);
            }
        });
        resultB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                resultBKeyPressed(evt);
            }
        });

        resultD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultDActionPerformed(evt);
            }
        });
        resultD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                resultDKeyPressed(evt);
            }
        });

        resultF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultFActionPerformed(evt);
            }
        });
        resultF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                resultFKeyPressed(evt);
            }
        });

        resultH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultHActionPerformed(evt);
            }
        });
        resultH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                resultHKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("km");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("km");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("km");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("km");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("km");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setText("km");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setText("km");

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel32.setText("km");

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel35.setText("km");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(8, 8, 8)
                        .addComponent(lbl1)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel4)
                        .addGap(5, 5, 5)
                        .addComponent(resultA, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel21)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel31)
                        .addGap(8, 8, 8)
                        .addComponent(lbl2)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel33)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel34)
                        .addGap(8, 8, 8)
                        .addComponent(resultB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel24))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(8, 8, 8)
                        .addComponent(lbl3)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel9)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel10)
                        .addGap(6, 6, 6)
                        .addComponent(resultC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel27)
                        .addGap(8, 8, 8)
                        .addComponent(lbl4)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel29)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel30)
                        .addGap(7, 7, 7)
                        .addComponent(resultD, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel28))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(8, 8, 8)
                        .addComponent(lbl5)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel14)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel11)
                        .addGap(8, 8, 8)
                        .addComponent(resultE, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel12)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel23)
                        .addGap(8, 8, 8)
                        .addComponent(lbl6)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel25)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel26)
                        .addGap(10, 10, 10)
                        .addComponent(resultF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel32))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(8, 8, 8)
                        .addComponent(lbl7)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel18)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel15)
                        .addGap(5, 5, 5)
                        .addComponent(resultG, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel17)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel20)
                        .addGap(8, 8, 8)
                        .addComponent(lbl8)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel19)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel22)
                        .addGap(6, 6, 6)
                        .addComponent(resultH, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel35))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addGap(8, 8, 8)
                        .addComponent(lbl9)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel38)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(resultI, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbl1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addComponent(resultA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel31))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lbl2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel33))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel34))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(resultB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel24)))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lbl3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel10))
                    .addComponent(resultC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel27))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbl4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel29))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel30))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(resultD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel28)))
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel13))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lbl5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel14))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel11))
                    .addComponent(resultE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel23))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lbl6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel25))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel26))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(resultF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel32)))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel20)
                    .addComponent(lbl8)
                    .addComponent(jLabel19)
                    .addComponent(jLabel22)
                    .addComponent(resultH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(lbl7)
                            .addComponent(jLabel18)
                            .addComponent(jLabel15))))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36)
                    .addComponent(lbl9)
                    .addComponent(jLabel38)
                    .addComponent(jLabel39)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resultI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))))
        );

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 490, 180));

        lbl_instruction1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_instruction1.setText("Puzzle - ");
        jPanel4.add(lbl_instruction1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 560, 730));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void resultHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultHActionPerformed


    private void resultFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultFActionPerformed

    private void resultDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultDActionPerformed

    private void resultBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultBActionPerformed

    private void resultIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultIActionPerformed

    private void resultGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultGActionPerformed

    private void resultCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultCActionPerformed

    private void resultEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultEActionPerformed

    private void resultAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultAActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

        if (resultA.getText().equals("") || resultB.getText().equals("") || 
                resultC.getText().equals("") || resultD.getText().equals("") ||
                resultE.getText().equals("") || resultF.getText().equals("") || 
                resultG.getText().equals("") || resultH.getText().equals("") ||
                resultI.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please insert values");
        } else {
            int AResult = Integer.parseInt(resultA.getText());
            int BResult = Integer.parseInt(resultB.getText());
            int CResult = Integer.parseInt(resultC.getText());
            int DResult = Integer.parseInt(resultD.getText());
            int EResult = Integer.parseInt(resultE.getText());
            int FResult = Integer.parseInt(resultF.getText());
            int GResult = Integer.parseInt(resultG.getText());
            int HResult = Integer.parseInt(resultH.getText());
            int IResult = Integer.parseInt(resultI.getText());

            inputs = new int[]{AResult, BResult, CResult, DResult, EResult, FResult, GResult, HResult, IResult};
            saveInput = new String[]{point, "A", Integer.toString(AResult),
                point, "B", Integer.toString(BResult),
                point, "C", Integer.toString(CResult),
                point, "D", Integer.toString(DResult),
                point, "E", Integer.toString(EResult),
                point, "F", Integer.toString(FResult),
                point, "G", Integer.toString(GResult),
                point, "H", Integer.toString(HResult),
                point, "I", Integer.toString(IResult)};

//            System.out.println("inputs contents: " + Arrays.toString(inputs)); 
//            System.out.println("Answer contents: " + Arrays.toString(saveInput));
//            System.out.println("Answer Size: " +saveInput.length);
//            System.out.println("City Connections contents: " + Arrays.toString(cityConnections));
//            System.out.println("City Connections Size: " +cityConnections.length);
            boolean result = compare(inputs, shortest);
            if (result == true) {
                System.out.println("Sucess");
                //JOptionPane.showMessageDialog(null, "Your answer is Correct !");
                DijkstraMapSql djSql = new DijkstraMapSql(uid, uname, Arrays.toString(cityConnections), point, Arrays.toString(saveInput));
                djSql.saveAnswers();
            } else if (result == false) {
                JOptionPane.showMessageDialog(null, "Wrong Answer.", "Try Again!", JOptionPane.ERROR_MESSAGE);
            }

        }

    }//GEN-LAST:event_btnSubmitActionPerformed

    private boolean compare(int[] array1, int[] array2) {

        if (array1.length != array2.length) {
            return false;
        }

        for (int i = 0; i < array1.length; i++) {
            if (array1[i] != array2[i]) {
                return false;
            }
        }
        return true;
    }

    private void clear() {
        resultA.setText("");
        resultB.setText("");
        resultC.setText("");
        resultD.setText("");
        resultE.setText("");
        resultF.setText("");
        resultG.setText("");
        resultH.setText("");
        resultI.setText("");
    }
    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        clear();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void resultAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_resultAKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            resultA.setEditable(true);
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE) {
                resultA.setEditable(true);
            } else {
                JOptionPane.showMessageDialog(null, "Please insert integer values");
                resultA.setText("");
            }
        }
    }//GEN-LAST:event_resultAKeyPressed

    private void resultCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_resultCKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            resultC.setEditable(true);
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE) {
                resultC.setEditable(true);
            } else {
                JOptionPane.showMessageDialog(null, "Please insert integer values");
                resultC.setText("");
            }
        }
    }//GEN-LAST:event_resultCKeyPressed

    private void resultEKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_resultEKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            resultE.setEditable(true);
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE) {
                resultE.setEditable(true);
            } else {
                JOptionPane.showMessageDialog(null, "Please insert integer values");
                resultE.setText("");
            }
        }
    }//GEN-LAST:event_resultEKeyPressed


    private void resultGKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_resultGKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            resultG.setEditable(true);
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE) {
                resultG.setEditable(true);
            } else {
                JOptionPane.showMessageDialog(null, "Please insert integer values");
                resultG.setText("");
            }
        }
    }//GEN-LAST:event_resultGKeyPressed

    private void resultIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_resultIKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            resultI.setEditable(true);
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE) {
                resultI.setEditable(true);
            } else {
                JOptionPane.showMessageDialog(null, "Please insert integer values");
                resultI.setText("");
            }
        }
    }//GEN-LAST:event_resultIKeyPressed

    private void resultBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_resultBKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            resultB.setEditable(true);
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE) {
                resultB.setEditable(true);
            } else {
                JOptionPane.showMessageDialog(null, "Please insert integer values");
                resultB.setText("");
            }
        }
    }//GEN-LAST:event_resultBKeyPressed

    private void resultDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_resultDKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            resultD.setEditable(true);
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE) {
                resultD.setEditable(true);
            } else {
                JOptionPane.showMessageDialog(null, "Please insert integer values");
                resultD.setText("");
            }
        }
    }//GEN-LAST:event_resultDKeyPressed

    private void resultFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_resultFKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            resultF.setEditable(true);
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE) {
                resultF.setEditable(true);
            } else {
                JOptionPane.showMessageDialog(null, "Please insert integer values");
                resultF.setText("");
            }
        }
    }//GEN-LAST:event_resultFKeyPressed

    private void resultHKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_resultHKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            resultH.setEditable(true);
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE) {
                resultH.setEditable(true);
            } else {
                JOptionPane.showMessageDialog(null, "Please insert integer values");
                resultH.setText("");
            }
        }
    }//GEN-LAST:event_resultHKeyPressed

    private void lbl_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lbl_closeMouseClicked

    private void lbl_close3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_close3MouseClicked
        clear();
        this.setVisible(false);
        new Home(uid, uname).setVisible(true);
    }//GEN-LAST:event_lbl_close3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DijkstraMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DijkstraMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DijkstraMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DijkstraMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new DijkstraMap({1,2,3},"ee",{1,2,3}).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btn_clear;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl9;
    private javax.swing.JLabel lblAB;
    private javax.swing.JLabel lblAI;
    private javax.swing.JLabel lblBC;
    private javax.swing.JLabel lblBI;
    private javax.swing.JLabel lblCD;
    private javax.swing.JLabel lblDE;
    private javax.swing.JLabel lblEF;
    private javax.swing.JLabel lblFG;
    private javax.swing.JLabel lblHE;
    private javax.swing.JLabel lblHF;
    private javax.swing.JLabel lblHG;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblIH;
    private javax.swing.JLabel lbl_close;
    private javax.swing.JLabel lbl_close3;
    private javax.swing.JLabel lbl_instruction1;
    private javax.swing.JLabel lbl_instruction2;
    private javax.swing.JLabel lbl_userID;
    private javax.swing.JLabel lbl_userName;
    private javax.swing.JLabel lbl_userName1;
    private javax.swing.JTextField resultA;
    private javax.swing.JTextField resultB;
    private javax.swing.JTextField resultC;
    private javax.swing.JTextField resultD;
    private javax.swing.JTextField resultE;
    private javax.swing.JTextField resultF;
    private javax.swing.JTextField resultG;
    private javax.swing.JTextField resultH;
    private javax.swing.JTextField resultI;
    // End of variables declaration//GEN-END:variables
}
