/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Hadaragama
 */
import java.awt.event.KeyEvent;
import java.util.Random;
import java.util.PriorityQueue;
import java.util.HashMap;
import javax.swing.JOptionPane;

class HuffmanCode implements Comparable<HuffmanCode> {

    char character;
    int frequency;
    HuffmanCode left, right;

    /**
     * @param args the command line arguments
     */
    public HuffmanCode(char character, int frequency) {
        this.character = character;
        this.frequency = frequency;
    }

    public boolean isLeafNode() {
        return (left == null && right == null);
    }

    @Override
    public int compareTo(HuffmanCode other) {
        return this.frequency - other.frequency;
    }

}

class HuffamanEncoder {

    public static HashMap<Character, String> encode(String input) {
        HashMap<Character, Integer> frequencyMap = new HashMap<>();
        for (char c : input.toCharArray()) {
            frequencyMap.put(c, frequencyMap.getOrDefault(c, 0) + 1);
        }
        PriorityQueue<HuffmanCode> priorityQueue = new PriorityQueue<>();
        for (char c : frequencyMap.keySet()) {
            priorityQueue.offer(new HuffmanCode(c, frequencyMap.get(c)));
        }
        while (priorityQueue.size() > 1) {
            HuffmanCode leftChild = priorityQueue.poll();
            HuffmanCode rightChild = priorityQueue.poll();

            HuffmanCode parent = new HuffmanCode('\0', leftChild.frequency + rightChild.frequency);
            parent.left = leftChild;
            parent.right = rightChild;

            priorityQueue.offer(parent);
        }
        HuffmanCode root = priorityQueue.poll();
        HashMap<Character, String> encodingMap = new HashMap<>();
        buildEncodingMap(root, "", encodingMap);

        return encodingMap;
    }

    private static void buildEncodingMap(HuffmanCode node, String code, HashMap<Character, String> encodingMap) {
        if (node.isLeafNode()) {
            encodingMap.put(node.character, code);
            return;
        }

        buildEncodingMap(node.left, code + "0", encodingMap);
        buildEncodingMap(node.right, code + "1", encodingMap);
    }
}

public class EncodeHuffman extends javax.swing.JFrame {

    /**
     * Creates new form EncodeHuffman
     */
    int uid;
    String uname;
    Random random = new Random();
    int length = 10;

    public EncodeHuffman(int uid, String uname) {
        this.uname = uname;
        this.uid = uid;
        System.out.println("" + uid + uname);
        initComponents();
        lbl_userName.setText(uname);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lbl_close = new javax.swing.JLabel();
        lbl_userName1 = new javax.swing.JLabel();
        lbl_close3 = new javax.swing.JLabel();
        lbl_userID = new javax.swing.JLabel();
        lbl_userName = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_generateWord = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_userAnswer = new javax.swing.JTextPane();
        btn_submit = new javax.swing.JButton();
        lbl_string = new javax.swing.JLabel();
        btn_clear = new javax.swing.JButton();
        lbl_instruction1 = new javax.swing.JLabel();
        lbl_instruction2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(12, 19, 79));

        lbl_close.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbl_close.setForeground(new java.awt.Color(255, 255, 255));
        lbl_close.setText("X");
        lbl_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_closeMouseClicked(evt);
            }
        });

        lbl_userName1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_userName1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_userName1.setText("Encode Puzzle");

        lbl_close3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lbl_close3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_close3.setText("<Back");
        lbl_close3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_close3MouseClicked(evt);
            }
        });

        lbl_userID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_userID.setForeground(new java.awt.Color(255, 255, 255));
        lbl_userID.setText("Hello");

        lbl_userName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_userName.setForeground(new java.awt.Color(255, 255, 255));
        lbl_userName.setText("UserName");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbl_userID)
                .addGap(2, 2, 2)
                .addComponent(lbl_userName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_userName1)
                .addGap(127, 127, 127)
                .addComponent(lbl_close3)
                .addGap(18, 18, 18)
                .addComponent(lbl_close)
                .addGap(14, 14, 14))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_userID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_userName))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_close)
                        .addComponent(lbl_close3)
                        .addComponent(lbl_userName1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btn_generateWord.setBackground(new java.awt.Color(204, 255, 255));
        btn_generateWord.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_generateWord.setForeground(new java.awt.Color(12, 19, 79));
        btn_generateWord.setText("Generate String");
        btn_generateWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generateWordActionPerformed(evt);
            }
        });

        txt_userAnswer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_userAnswer.setForeground(new java.awt.Color(12, 19, 79));
        txt_userAnswer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_userAnswerKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(txt_userAnswer);

        btn_submit.setBackground(new java.awt.Color(204, 255, 255));
        btn_submit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_submit.setForeground(new java.awt.Color(12, 19, 79));
        btn_submit.setText("Submit");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });

        lbl_string.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_string.setForeground(new java.awt.Color(12, 19, 79));
        lbl_string.setText(".......................................................................................");

        btn_clear.setBackground(new java.awt.Color(204, 255, 255));
        btn_clear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_clear.setForeground(new java.awt.Color(12, 19, 79));
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        lbl_instruction1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_instruction1.setText("Puzzle - ");

        lbl_instruction2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_instruction2.setText("Generate a word and encode it to binary.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addComponent(btn_generateWord, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                                .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbl_instruction1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_instruction2, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(lbl_string, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_instruction2)
                    .addComponent(lbl_instruction1))
                .addGap(79, 79, 79)
                .addComponent(lbl_string, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btn_generateWord, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(211, 211, 211))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_generateWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generateWordActionPerformed
        // TODO add your handling code here:

        String toEncode = generateRandomString(5);
        lbl_string.setText(toEncode);

    }//GEN-LAST:event_btn_generateWordActionPerformed

    private void lbl_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lbl_closeMouseClicked

    private void lbl_close3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_close3MouseClicked
        clear();
        this.setVisible(false);
        new Home(uid, uname).setVisible(true);
    }//GEN-LAST:event_lbl_close3MouseClicked
    private void checkAnswer(String answer, String input) {
        if (input.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Generate a word First !", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (answer.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter answer !", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                HashMap<Character, String> encodingMap = HuffamanEncoder.encode(input);

                StringBuilder encodedMessage = new StringBuilder();

                for (char c : input.toCharArray()) {
                    encodedMessage.append(encodingMap.get(c));
                }

                if (answer.equals(encodedMessage.toString())) {
                    JOptionPane.showMessageDialog(this, "Your Answer is Correct!", "Congragulations!", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Your Answer is Incorrect! correct answer : " + encodedMessage.toString(), "Try Again", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }
    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // TODO add your handling code here:

        String answer = txt_userAnswer.getText();
        String input = lbl_string.getText();
        checkAnswer(answer, input);

    }//GEN-LAST:event_btn_submitActionPerformed
    private void clear() {
        lbl_string.setText("");
        txt_userAnswer.setText("");
    }
    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        clear();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void txt_userAnswerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_userAnswerKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '1') {
            txt_userAnswer.setEditable(true);
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE) {
                txt_userAnswer.setEditable(true);
            } else {
                JOptionPane.showMessageDialog(this, "Please enter "
                        + "Binary Value !", "Information", JOptionPane.ERROR_MESSAGE);

                txt_userAnswer.setText("");
            }
        }
    }//GEN-LAST:event_txt_userAnswerKeyPressed

    /**
     * @param args the command line arguments
     */
    private String generateRandomString(int length) {
        // Define the characters that can be used in the random string
        String characters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ123456780";

        StringBuilder sb = new StringBuilder(length);
        for (int i = 0; i < length; i++) {
            // Generate a random index within the range of available characters
            int randomIndex = random.nextInt(characters.length());

            // Append the character at the random index to the string
            sb.append(characters.charAt(randomIndex));
        }

        return sb.toString();
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EncodeHuffman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EncodeHuffman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EncodeHuffman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EncodeHuffman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EncodeHuffman(1, "UserName").setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_generateWord;
    private javax.swing.JButton btn_submit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_close;
    private javax.swing.JLabel lbl_close3;
    private javax.swing.JLabel lbl_instruction1;
    private javax.swing.JLabel lbl_instruction2;
    private javax.swing.JLabel lbl_string;
    private javax.swing.JLabel lbl_userID;
    private javax.swing.JLabel lbl_userName;
    private javax.swing.JLabel lbl_userName1;
    private javax.swing.JTextPane txt_userAnswer;
    // End of variables declaration//GEN-END:variables
}
