/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.DijkstraMapLogics;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Hadaragama
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
   static String uname;
    static int uid;
    public Home(int uid,String uname) {
        initComponents();
        this.uid=uid;
        this.uname=uname;
        
        //lbl_userID.setText(Integer.toString(uid));
        lbl_userName.setText(uname);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_EightQueens = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbl_userID = new javax.swing.JLabel();
        lbl_userName = new javax.swing.JLabel();
        lbl_close = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_MinimumConnectors = new javax.swing.JButton();
        btn_encodeHuffman = new javax.swing.JButton();
        btn_TicTacToe = new javax.swing.JButton();
        btn_ShortestPath = new javax.swing.JButton();
        btn_decodeHuffman = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btn_EightQueens.setBackground(new java.awt.Color(204, 255, 255));
        btn_EightQueens.setText("Eight Queens Puzzle");
        btn_EightQueens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EightQueensActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(12, 19, 79));
        jPanel2.setMinimumSize(new java.awt.Dimension(0, 0));

        lbl_userID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_userID.setForeground(new java.awt.Color(255, 255, 255));
        lbl_userID.setText("Hello");

        lbl_userName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_userName.setForeground(new java.awt.Color(255, 255, 255));
        lbl_userName.setText("UserName");

        lbl_close.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbl_close.setForeground(new java.awt.Color(255, 255, 255));
        lbl_close.setText("X");
        lbl_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_closeMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chamod Dilushanka\\Downloads\\icons8-user-50 (1).png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_userID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_userName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_close)
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lbl_close))
                .addGap(0, 8, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_userID)
                    .addComponent(lbl_userName))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_MinimumConnectors.setBackground(new java.awt.Color(204, 255, 255));
        btn_MinimumConnectors.setText("Find Minimum Connectors");
        btn_MinimumConnectors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MinimumConnectorsActionPerformed(evt);
            }
        });

        btn_encodeHuffman.setBackground(new java.awt.Color(204, 255, 255));
        btn_encodeHuffman.setText("Encode Word Puzzle");
        btn_encodeHuffman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_encodeHuffmanActionPerformed(evt);
            }
        });

        btn_TicTacToe.setBackground(new java.awt.Color(204, 255, 255));
        btn_TicTacToe.setText("TicTac Toe");
        btn_TicTacToe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TicTacToeActionPerformed(evt);
            }
        });

        btn_ShortestPath.setBackground(new java.awt.Color(204, 255, 255));
        btn_ShortestPath.setText("Find Shortest Path");
        btn_ShortestPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ShortestPathActionPerformed(evt);
            }
        });

        btn_decodeHuffman.setBackground(new java.awt.Color(204, 255, 255));
        btn_decodeHuffman.setText("Decode Word Puzzle");
        btn_decodeHuffman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_decodeHuffmanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_MinimumConnectors, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                    .addComponent(btn_ShortestPath, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_TicTacToe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_encodeHuffman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_EightQueens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_decodeHuffman, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_EightQueens, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_encodeHuffman, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_decodeHuffman, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_TicTacToe, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_ShortestPath, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_MinimumConnectors, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lbl_closeMouseClicked

    private void btn_EightQueensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EightQueensActionPerformed
        int solutions = 12;
        int answer = Integer.parseInt(JOptionPane.showInputDialog(null,"Eight chess queens must be placed \n" +
            "on an 8x8 chessboard in such a way that no two queens threaten each other.\n" +"How many solutions for this puzzle?"));
    if (solutions==answer) {
        JOptionPane.showMessageDialog(null, "Your Answer is Correct.","Congragulations!",JOptionPane.INFORMATION_MESSAGE);
        this.setVisible(false);
        new EightQueens(uid,uname).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Your Answer is Incorrect.","Try Again!",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_EightQueensActionPerformed

    private void btn_MinimumConnectorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MinimumConnectorsActionPerformed
        this.setVisible(false);new MinimumConnectors(uid,uname).setVisible(true);
    }//GEN-LAST:event_btn_MinimumConnectorsActionPerformed

    private void btn_encodeHuffmanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_encodeHuffmanActionPerformed
       this.setVisible(false);new EncodeHuffman(uid,uname).setVisible(true);
        
    }//GEN-LAST:event_btn_encodeHuffmanActionPerformed

    private void btn_TicTacToeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TicTacToeActionPerformed
        TicTacToe tictac=new TicTacToe();
        tictac.setVisible(true);
    }//GEN-LAST:event_btn_TicTacToeActionPerformed

    private void btn_ShortestPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ShortestPathActionPerformed
        this.setVisible(false);new DijkstraMapLogics(uid,uname);
    }//GEN-LAST:event_btn_ShortestPathActionPerformed

    private void btn_decodeHuffmanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_decodeHuffmanActionPerformed
        this.setVisible(false);new DecodeHuffman(uid,uname).setVisible(true);
    }//GEN-LAST:event_btn_decodeHuffmanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home(uid,"user").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_EightQueens;
    private javax.swing.JButton btn_MinimumConnectors;
    private javax.swing.JButton btn_ShortestPath;
    private javax.swing.JButton btn_TicTacToe;
    private javax.swing.JButton btn_decodeHuffman;
    private javax.swing.JButton btn_encodeHuffman;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_close;
    private javax.swing.JLabel lbl_userID;
    private javax.swing.JLabel lbl_userName;
    // End of variables declaration//GEN-END:variables
}
