/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.ManageUsers;
import javax.swing.JOptionPane;

/**
 *
 * @author Hadaragama
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_register = new javax.swing.JLabel();
        lbl_uname = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        lbl_pwd = new javax.swing.JLabel();
        lbl_cpwd = new javax.swing.JLabel();
        btn_register = new javax.swing.JButton();
        txt_uname1 = new javax.swing.JTextField();
        txt_uemail = new javax.swing.JTextField();
        txt_upwd = new javax.swing.JPasswordField();
        txt_ucpwd = new javax.swing.JPasswordField();
        lbl_close = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(803, 500));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));

        lbl_register.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        lbl_register.setForeground(new java.awt.Color(12, 19, 79));
        lbl_register.setText("Register");

        lbl_uname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_uname.setText("User Name");

        lbl_email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_email.setText("Email");

        lbl_pwd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_pwd.setText("Password");

        lbl_cpwd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_cpwd.setText("Confirm Password");

        btn_register.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btn_register.setForeground(new java.awt.Color(12, 19, 79));
        btn_register.setText("Register");
        btn_register.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(8, 131, 149)));
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });

        txt_uname1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txt_uname1.setForeground(new java.awt.Color(51, 51, 51));
        txt_uname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_uname1ActionPerformed(evt);
            }
        });

        txt_uemail.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txt_uemail.setForeground(new java.awt.Color(51, 51, 51));
        txt_uemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_uemailActionPerformed(evt);
            }
        });

        txt_upwd.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txt_upwd.setForeground(new java.awt.Color(51, 51, 51));

        txt_ucpwd.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txt_ucpwd.setForeground(new java.awt.Color(51, 51, 51));

        lbl_close.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbl_close.setForeground(new java.awt.Color(12, 19, 79));
        lbl_close.setText("X");
        lbl_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_closeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_register)
                        .addGap(123, 123, 123)
                        .addComponent(lbl_close)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_cpwd)
                            .addComponent(lbl_uname)
                            .addComponent(txt_uname1)
                            .addComponent(lbl_email)
                            .addComponent(txt_uemail)
                            .addComponent(lbl_pwd)
                            .addComponent(txt_upwd)
                            .addComponent(txt_ucpwd, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_register, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lbl_register))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_close, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(lbl_uname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_uname1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_uemail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_pwd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_upwd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_cpwd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_ucpwd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btn_register, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        jPanel2.setBackground(new java.awt.Color(12, 19, 79));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chamod Dilushanka\\Downloads\\image-removebg-preview (29).png")); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(819, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        String uname = txt_uname1.getText();
        String uemail = txt_uemail.getText();
        String upwd = txt_upwd.getText();
        String ucpwd = txt_ucpwd.getText();
        
        if (uname.isEmpty()) {
            JOptionPane.showMessageDialog(this, "User Name should not be empty","Error",JOptionPane.ERROR_MESSAGE);
        } else if(uemail.isEmpty()){
            JOptionPane.showMessageDialog(this, "User Email should not be empty","Error",JOptionPane.ERROR_MESSAGE);
        }else if(upwd.isEmpty()){
            JOptionPane.showMessageDialog(this, "User Password should not be empty","Error",JOptionPane.ERROR_MESSAGE);
        }else if(ucpwd.isEmpty()){
            JOptionPane.showMessageDialog(this, "User Confrim Password should not be empty","Error",JOptionPane.ERROR_MESSAGE);
        }else if(!(ucpwd.equals(upwd))){
            JOptionPane.showMessageDialog(this, "User Password and Confirm Password not matching.","Error",JOptionPane.ERROR_MESSAGE);
        }else{
            txt_uname1.setText("");
            txt_upwd.setText("");
            txt_uemail.setText("");
            txt_ucpwd.setText("");
            ManageUsers mUser = new ManageUsers();
            mUser.setInputSignUp(uname,uemail, upwd);
            this.setVisible(false);
        }
        
   
    }//GEN-LAST:event_btn_registerActionPerformed

    private void txt_uname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_uname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_uname1ActionPerformed

    private void txt_uemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_uemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_uemailActionPerformed

    private void lbl_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lbl_closeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_register;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_close;
    private javax.swing.JLabel lbl_cpwd;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_pwd;
    private javax.swing.JLabel lbl_register;
    private javax.swing.JLabel lbl_uname;
    private javax.swing.JPasswordField txt_ucpwd;
    private javax.swing.JTextField txt_uemail;
    private javax.swing.JTextField txt_uname1;
    private javax.swing.JPasswordField txt_upwd;
    // End of variables declaration//GEN-END:variables
}
