/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.ManageUsers;
import Model.SqlConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Hadaragama
 */
public class SignIn extends javax.swing.JFrame {

    /**
     * Creates new form SignIn
     */

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public SignIn() {
        con = SqlConnection.myCon();  
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        lbl_pwd = new javax.swing.JLabel();
        lbl_signin = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        btn_signin = new javax.swing.JButton();
        lbl_notHaveAccount = new javax.swing.JLabel();
        lbl_welcome = new javax.swing.JLabel();
        txt_upwd = new javax.swing.JPasswordField();
        lbl_close = new javax.swing.JLabel();
        lbl_notHaveAccount1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(0, 0, 102));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setPreferredSize(new java.awt.Dimension(800, 500));

        lbl_pwd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_pwd.setForeground(new java.awt.Color(12, 19, 79));
        lbl_pwd.setText("Password");

        lbl_signin.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbl_signin.setForeground(new java.awt.Color(12, 19, 79));
        lbl_signin.setText("LOGIN");

        lbl_username.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_username.setForeground(new java.awt.Color(12, 19, 79));
        lbl_username.setText("User Name");

        txt_username.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txt_username.setForeground(new java.awt.Color(51, 51, 51));
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });

        btn_signin.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btn_signin.setForeground(new java.awt.Color(12, 19, 79));
        btn_signin.setText("Sign in");
        btn_signin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(12, 19, 79)));
        btn_signin.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btn_signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signinActionPerformed(evt);
            }
        });

        lbl_notHaveAccount.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        lbl_notHaveAccount.setForeground(new java.awt.Color(102, 102, 102));
        lbl_notHaveAccount.setText("Don't have an account yet?");

        lbl_welcome.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        lbl_welcome.setForeground(new java.awt.Color(12, 19, 79));
        lbl_welcome.setText("Hello Again!");

        txt_upwd.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txt_upwd.setForeground(new java.awt.Color(51, 51, 51));
        txt_upwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_upwdActionPerformed(evt);
            }
        });

        lbl_close.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbl_close.setForeground(new java.awt.Color(12, 19, 79));
        lbl_close.setText("X");
        lbl_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_closeMouseClicked(evt);
            }
        });

        lbl_notHaveAccount1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        lbl_notHaveAccount1.setText("Register");
        lbl_notHaveAccount1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_notHaveAccount1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(lbl_notHaveAccount)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_notHaveAccount1))
                            .addComponent(lbl_username, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_username)
                            .addComponent(lbl_pwd, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_upwd, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
                        .addGap(86, 86, 86))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addComponent(lbl_welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(lbl_close, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addComponent(lbl_signin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152))))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(btn_signin, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lbl_welcome, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                        .addGap(32, 32, 32))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_close)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(lbl_signin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(lbl_username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_pwd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_upwd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btn_signin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_notHaveAccount)
                    .addComponent(lbl_notHaveAccount1))
                .addGap(94, 94, 94))
        );

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 0, 410, -1));

        jPanel1.setBackground(new java.awt.Color(12, 19, 79));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 180, 150));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chamod Dilushanka\\Downloads\\image-removebg-preview (27).png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, -10, 390, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void btn_signinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signinActionPerformed
        String uname = txt_username.getText();
        String upwd = txt_upwd.getText();
        if (uname.isEmpty()) {
            JOptionPane.showMessageDialog(this, "User Name should not be empty","Error",JOptionPane.ERROR_MESSAGE);
        } else if(upwd.isEmpty()){
            JOptionPane.showMessageDialog(this, "User Password should not be empty","Error",JOptionPane.ERROR_MESSAGE);
        }else{
            txt_username.setText("");
            txt_upwd.setText("");
            ManageUsers mUser = new ManageUsers();
            mUser.setInputSignIn(uname, upwd);
            this.setVisible(false);
        }       
    }//GEN-LAST:event_btn_signinActionPerformed

    private void txt_upwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_upwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_upwdActionPerformed

    private void lbl_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lbl_closeMouseClicked

    private void lbl_notHaveAccount1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_notHaveAccount1MouseClicked
        this.setVisible(false);
        new SignUp().setVisible(true);
    }//GEN-LAST:event_lbl_notHaveAccount1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_signin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_close;
    private javax.swing.JLabel lbl_notHaveAccount;
    private javax.swing.JLabel lbl_notHaveAccount1;
    private javax.swing.JLabel lbl_pwd;
    private javax.swing.JLabel lbl_signin;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JLabel lbl_welcome;
    private javax.swing.JPanel panel1;
    private javax.swing.JPasswordField txt_upwd;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
