/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Hadaragama
 */
import Controller.TicTacToeLogics;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
public class TicTacToe extends javax.swing.JFrame implements ActionListener {

    private static final int sizeLayout = 3;
    private static final char userInput = 'X';
    private static final char aiComputer = 'O';
    private static final char Enull = '-';

    private JButton[][] buttons;
    private TicTacToeLogics game;
    /**
     * Creates new form TicTacToeUI
     */
    public TicTacToe() {
        initComponents();
        game=new TicTacToeLogics();
        setTitle("Tic Tac Toe");
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        setSize(560, 700);
        setLayout(new GridLayout(sizeLayout, sizeLayout));
        buttons = new JButton[sizeLayout][sizeLayout];
        
        for (int i = 0; i < sizeLayout; i++) {
            for (int j = 0; j < sizeLayout; j++) {
                buttons[i][j] = new JButton();
                buttons[i][j].setBackground(new java.awt.Color(204,255,255));
                buttons[i][j].setFont(new Font(Font.SANS_SERIF, Font.BOLD, 60));
                buttons[i][j].addActionListener(this);
                add(buttons[i][j]);
            }
        }
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(12, 19, 79));
        setPreferredSize(new java.awt.Dimension(560, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void actionPerformed(ActionEvent e){
    
     JButton button = (JButton) e.getSource();
     for (int i = 0; i < sizeLayout; i++) {
            for (int j = 0; j < sizeLayout; j++) {
     if (button == buttons[i][j] && game.isMoveValid(i, j) && !game.isGameOver()) {
                    game.makeMove(i, j, userInput);
                    button.setText(Character.toString(userInput));
                    
                    if (!game.isGameOver()) {
                        game.makeAIMove();
                        int computerRow = game.getComputerMoveRow();
                        int computerCol = game.getComputerMoveCol();
                        buttons[computerRow][computerCol].setText(Character.toString(aiComputer));
                    }

                    if (game.isGameOver()) {
                        if (game.tryWinner(userInput)) {
                           
                            JOptionPane.showMessageDialog(this, "Wow, You win !","Congradulations",JOptionPane.INFORMATION_MESSAGE);
                        } else if (game.tryWinner(aiComputer)) {
                            JOptionPane.showMessageDialog(this, "Unlucky, Computer win !","Try Again",JOptionPane.INFORMATION_MESSAGE);
                        } else {
                            JOptionPane.showMessageDialog(this, "Nice Try, Draw game !","Try Again",JOptionPane.INFORMATION_MESSAGE);
                        }
                        reset();
                    }
                }
            }
        
     }
    
    }
    public void reset() {
        game = new TicTacToeLogics();
        for (int i = 0; i < sizeLayout; i++) {
            for (int j = 0; j < sizeLayout; j++) {
                buttons[i][j].setText("");
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new TicTacToe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
